version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: countrydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run serve

volumes:
  pgdata:
