services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: verbup-be
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    env_file:
      - .env.development.local
    volumes:
      - .:/app
    command: npm run serve:full

volumes:
  pgdata:
