openapi: 3.0.0
info:
  title: Verbup API
  version: 1.0.0
  description: API documentation for Verbup

tags:
  - name: Auth
    description: Authentication & authorization endpoints
  - name: Users
    description: User management endpoints
  - name: Feedbacks
    description: Feedback management endpoints

servers:
  - url: http://localhost:8000/api/v1

paths:
  /auth/register:
    post:
      $ref: './paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: './paths/auth/login.yaml'
  /auth/verify-email:
    get:
      $ref: './paths/auth/verify-email.yaml'
  /auth/refresh:
    post:
      $ref: './paths/auth/refresh.yaml'
  /users:
    # post:
    #   $ref: './paths/users/create.yaml'
    # get:
    #   $ref: './paths/users/getAll.yaml'
    get:
      $ref: './paths/users/get.yaml'
    patch:
      $ref: './paths/users/patch.yaml'
    delete:
      $ref: './paths/users/delete.yaml'
  /feedback:
    post:
      $ref: './paths/feedback/create.yaml'
    # get:
    #   $ref: './patch/feedback/getAll.yaml'
  /games/words:
    $ref: './paths/games.yaml'
  /irr-words/{lang}/list:
    get:
      $ref: './paths/irr-words/list.yaml'
  /irr-words/image:
    post:
      $ref: './paths/irr-words/addImage.yaml'
    get:
      $ref: './paths/irr-words/getImage.yaml'
  /progress:
    post:
      $ref: './paths/progress/save.yaml'
    get:
      $ref: './paths/progress/list.yaml'
  /upload/image:
    post:
      $ref: './paths/upload.yaml'

components:
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
